### model
model_name_or_path: CohereForAI/aya-expanse-8b

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: crystall_ball_20241025
template: llama3
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/models/saves/aya-expanse-8b/lora/crystall_ball_20241025
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

lora_rank: 32
lora_alpha: 64


### train
per_device_train_batch_size: 10
gradient_accumulation_steps: 20
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
