### model
model_name_or_path: google/gemma-2-9b-it

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: crystall_ball_merge
template: gemma #llama3
cutoff_len: 1024
max_samples: 249900
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/models/saves/gemma-2-9b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 10
gradient_accumulation_steps: 20
learning_rate: 5.0e-5 #1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
lora_rank: 64
lora_alpha: 128
#lora_dropout: 0.1


### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
