### model
model_name_or_path: /data/models/saves/qwen2.5-32b/lora/sft_instruction_nl2sql_20250113_merge

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: nl2sql
template: qwen
cutoff_len: 1024
max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/models/saves/qwen2.5-32b/lora/sft_instruction_nl2sql_hardware_20250116
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
lora_rank: 32
lora_alpha: 64

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

